---
title: "Ciencia de Datos en Salud: Aplicaciones en CDC Perú"
author: "Andree Valle Campos, Candidato a Magíster en Ciencias de la Investigación Epidemiológica. Grupo de Trabajo en Investigación Epidemiológica y Evaluación de Intervenciones Sanitarias. (avallecam\\@gmail.com)"
date: '`r Sys.Date()`'
output: word_document
bibliography: "20191208-cdc_editorial.bib"
link-citations: yes
csl: american-medical-association.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- # introducción con presentación de ideas 1, 2, 3 -->
La Ciencia de Datos en Salud es el trabajo científico realizado para mejorar la colecta, 
manejo y análisis de datos de individuos o poblaciones, con el objetivo de mejorar su salud 
[@dammann2019health]. Este integra tres componentes: tecnologías de la información, 
métodos bioestadísticos y epidemiológicos, y un marco conceptual basado 
en salud pública e inferencia causal.
En CDC Perú, hay una creciente necesidad por tomar decisiones basadas en el análisis de grandes bases de datos existentes o 
la adquisición rápida de nueva información de campo.
Esto ha demandado que los epidemiólogos empecemos a usar activamente estas nuevas formas de trabajo.
En este sentido, aquí presentamos las características de tres herramientas de Software Libre [@lowndes2017our]
recientemente implementadas en la institución: KoBo Toolbox para 
la colecta de datos,  R para la limpieza de bases, y paquetes del 
R Epidemics Consortium (RECON) para el análisis cuantitativo en respuesta a brotes y epidemias.

<!-- # desarrollo de idea clave 1 -->
Primero, en situaciones de emergencia, el tiempo entre el diseño y la aplicación de una encuesta es 
crítico para evaluar hipótesis e implementar medidas de control.
KoBo Toolbox [@pham2018kobotoolbox] es una plataforma web que 
reduce este tiempo mediante el acceso a plantillas y medios rápidos de distribución. 
En comparación a otros softwares, su principal ventaja radica en el acceso a colecciones públicas de instrumentos compartidos 
por otras instituciones, acelerando la actividad científica bajo principios de Ciencia Abierta [@lowndes2017our]. 
También permite importar encuestas diseñadas en archivos Excel 
con formato XLSform [@xlsform2019], modificarlas en línea, usarlas en web o aplicativo móvil 
(KoBoCollect) [@kobocollect2019] para colectar información sin conexión a internet. 
En nuestra primera experiencia solo la empleamos como herramienta de digitación de encuestas llenadas a lápiz y papel. 
Sin embargo, el formato XLSform permitió la edición colaborativa vía Google Sheets reduciendo el tiempo de diseño y distribución. 
Del mismo modo, la base de datos exportada conservó tipos de variable y etiquetas facilitando su análisis.

<!-- # desarrollo de idea clave 2 -->
Posterior a ello, todo proceso realizado debe ser reproducible, es decir estar escrito en 
código informático capaz de recrear todos los resultados a partir de los datos originales en cualquier momento [@rodriguez2016ciencia].
Empleamos el software de programación estadística R [@rcoreteam2019] para escribir nuestros procedimientos. 
En una sola plataforma permite importar, limpiar, 
analizar y generar reportes en formato de artículos [@rticles2019], presentaciones [@xaringan2019] o pósters [@posterdown2019]. 
Su disponibilidad de herramientas para la limpieza y resumen de bases [@grolemund2018r] ha permitido 
integrar múltiples fuentes de información de diferentes instituciones con estructuras totalmente heterogéneas.
Dos ejemplos son la generación de la lista de Enfermedades Raras o Huérfanas, y 
la lista de enfermedades priorizadas para el Plan Esencial de Aseguramiento en Salud. 
Ambos podrán reproducirse en cualquier momento para evaluar sus metodologías o actualizarlos 
en los próximos años ante la disponibilidad de nuevas bases de datos.

<!-- # desarrollo de idea clave 3 -->
Por otra parte, los análisis más especializados requieren de paquetes de R, 
los cuales son un conjunto de funciones que extienden la caja de herramientas que el software posee por defecto. 
RECON [@recon2019] es la agrupación que crea, integra y evalúa paquetes específicos
para el análisis de brotes, emergencias en salud y crisis humanitarias.
Por ejemplo, los paquetes _incidence_ y _projections_ modelan y proyectan incidencias en periodos cortos de tiempo, 
respectivamente [@polonsky2019outbreak]. 
Su amplia disponibilidad de tutoriales [@reconlearn2019] facilitó su rápida implementación en respuesta a la 
epidemia del Síndrome Guillain Barré del presente año [@munayco2019]. 
Además, recientes métodos de análisis estadísticos a escala espacial [@moraga2019geospatial]
permitieron generar mapas con riesgos relativos estimados a nivel distrital y 
evaluar su asociación con enfermedad diarreica aguda [@sgb2019]. 
De la misma forma, se podrán adaptar otros recursos como la generación estandarizada y automatizada de Salas Situacionales 
empleando el paquete _sitrep_ de la organización internacional R4epis [@r4epis2019].

<!-- (Otros son forecast para el pronóstico y incidencias mensuales ysurveillance para la detección de anomalías.)-->
<!-- # cierre -->
En resumen, el CDC Perú ha implementado herramientas de Ciencias de Datos en Salud 
que han acelerado la colecta, análisis y reporte en respuesta a brotes, epidemias, 
situaciones de emergencia e investigaciones epidemiológicas. 
Finalmente, experiencias similares en otros campos han demostrado que esta transición ha favorecido 
a la transparencia, el ahorro de esfuerzos y la estandarización de procesos al largo plazo, 
acortando el tiempo para la toma de decisiones [@lowndes2017our].
Por ello, los próximos pasos son capacitar y estimular el uso de estas herramientas en 
la institución y en las distintas Direcciones Regionales. 

El presente editorial ha sido generado usando Rmarkdown [@rmarkdown2018; @rmarkdown2019] 
y está disponible en GitHub [@cdcdatasci19].



# Referencias

